In [1]:
import numpy as np
import urllib.request
import pandas as pd

In [26]:
kanta = [21, 12, 22]
johta = [44, 65, 11]
hoenn = [99, 6, 4]
sinnoh = [47, 87, 5]
unova = [12,76, 99]

In [27]:
w1, w2, w3 = 0.3, 0.2, 0.5
weight = [w1, w2, w3]

In [39]:
def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result

print(crop_yield(kanta, weight))  # Output: 32


19.7


In [37]:
kanta = np.array(kanta)
type(kanta)
weight = np.array(weight)
type(weight)

numpy.ndarray

In [40]:
np.dot(kanta, weight)

19.7

In [42]:
(kanta* weight).sum()

19.7

In [44]:
climateData= np.array([
    [21, 12, 22], [44, 65, 11], [12,76, 99], [99, 6, 4], [47, 87, 5]
])
climateData

array([[21, 12, 22],
       [44, 65, 11],
       [12, 76, 99],
       [99,  6,  4],
       [47, 87,  5]])

In [45]:
climateData.shape

(5, 3)

In [46]:
weight.shape

(3,)

In [47]:
climateData.dtype

dtype('int32')

In [48]:
weight.dtype

dtype('float64')

In [49]:
np.matmul(climateData, weight)

array([19.7, 31.7, 68.3, 32.9, 34. ])

In [51]:
np.dot(climateData, weight)

array([19.7, 31.7, 68.3, 32.9, 34. ])

In [82]:
df = pd.read_csv(r"C:\Users\Omen\Downloads\testResponse.csv", delimiter=";")
print(df.head())

   temprature  rainfall  humidity
0        47.0      59.0      83.0
1        49.0      18.0      10.0
2        45.0      57.0      58.0
3        87.0      65.0       5.0
4        33.0      10.0      60.0


In [92]:
climateData=df.to_numpy()
climateData.shape

(100, 3)

In [93]:
climateData=np.delete(climateData, 0, axis=0)
climateData.shape

(99, 3)

In [94]:
yields = climateData@weight
yields

array([23.3, 53.9, 41.6, 41.9, 30.5, 73. , 61.3, 58.4, 40.6, 19.9, 58.7,
       57.5, 30.1, 66.4, 44.4, 49.8, 66.3, 54.2, 70.7, 89.4, 35.8, 33.4,
       24.2, 72.7, 70.2, 36. , 36.5, 65.4, 60.2, 40.9, 55.9, 39. , 33.2,
       66.1, 78.9, 64.2, 53.4, 50.8, 17.9, 41.6, 26.1, 35.9, 80.4, 61. ,
       45. , 76.9, 42.6, 30.8, 47.1, 65.3, 34.4, 42.5, 27.7, 47.6, 39.6,
       68.3, 49.3, 32.1, 71.8, 70.8, 36.6, 14.4, 79.8, 46. , 29. , 31.5,
       74.7, 73.4, 80.4, 59.9, 26.2, 43.7, 36.1, 76.6, 35.6, 66.6, 46.2,
       25.5, 58.7, 54.9, 32.8, 61.3, 57.2, 50. , 52.7, 14.1, 31.4, 45.2,
       37.5, 25.5, 36.3, 43.9, 67.7, 46.7, 55.1, 55.2, 55.7, 60.4, 54.7])

In [95]:
yields.shape

(99,)

In [97]:
climateResult = np.concatenate((climateData, yields.reshape(99, 1)), axis=1)
climateResult

array([[49. , 18. , 10. , 23.3],
       [45. , 57. , 58. , 53.9],
       [87. , 65. ,  5. , 41.6],
       [33. , 10. , 60. , 41.9],
       [ 6. , 81. , 25. , 30.5],
       [70. , 45. , 86. , 73. ],
       [32. , 61. , 79. , 61.3],
       [20. , 17. , 98. , 58.4],
       [85. , 73. ,  1. , 40.6],
       [ 1. , 58. , 16. , 19.9],
       [74. , 85. , 39. , 58.7],
       [88. , 38. , 47. , 57.5],
       [27. ,  5. , 42. , 30.1],
       [39. , 31. , 97. , 66.4],
       [93. , 40. , 17. , 44.4],
       [62. , 66. , 36. , 49.8],
       [12. , 91. , 89. , 66.3],
       [97. , 13. , 45. , 54.2],
       [86. , 37. , 75. , 70.7],
       [91. , 93. , 87. , 89.4],
       [18. , 92. , 24. , 35.8],
       [26. , 33. , 38. , 33.4],
       [ 7. , 88. ,  9. , 24.2],
       [56. , 32. , 99. , 72.7],
       [78. , 29. , 82. , 70.2],
       [15. , 75. , 33. , 36. ],
       [34. , 39. , 37. , 36.5],
       [35. , 82. , 77. , 65.4],
       [ 8. , 49. , 96. , 60.2],
       [68. , 15. , 35. , 40.9],
       [61

In [106]:
np.savetxt("climateResult.txt", climateResult, 
           fmt="%.2f",
           header="temperature,rainfall,humidity, yeild_apples",
           comments="important comment\n")

In [113]:
arr1=np.array([[1,2 ,3], [2,2, 34], [11, 3, 1]])
arr2=np.array([1, 23, 2])
arr1+arr2

array([[ 2, 25,  5],
       [ 3, 25, 36],
       [12, 26,  3]])

In [116]:
arr1==arr2

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [119]:
arr3 = arr1[1:, 2:3]
arr3

array([[34],
       [ 1]])

In [120]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [122]:
np.ones([1, 10, 3])

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [124]:
np.random.rand(2, 2, 3, 1)

array([[[[0.26723468],
         [0.03869189],
         [0.7641504 ]],

        [[0.40779399],
         [0.83601395],
         [0.04307978]]],


       [[[0.55325519],
         [0.38573054],
         [0.94577144]],

        [[0.81602692],
         [0.87081167],
         [0.92754588]]]])

In [125]:
np.arange(10, 45, 5)

array([10, 15, 20, 25, 30, 35, 40])

In [130]:
np.arange(10, 70, 5).reshape(3,2,2)

array([[[10, 15],
        [20, 25]],

       [[30, 35],
        [40, 45]],

       [[50, 55],
        [60, 65]]])

In [135]:
np.linspace(2, 10, 13)

array([ 2.        ,  2.66666667,  3.33333333,  4.        ,  4.66666667,
        5.33333333,  6.        ,  6.66666667,  7.33333333,  8.        ,
        8.66666667,  9.33333333, 10.        ])